version: '3.8'

services:
  web:
    restart: always
    build: .
    command: python author_app.py
    ports:
      - '5000:5000'
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    env_file:
      - .postgresenv
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always

volumes:
  db-data:
