version: '3.8'

services:
  web:
    restart: always
    build: .
    command: >
      sh -c "python author_app.py wait_for_db &&
             python author_app.py upgrade &&
             python author_app.py runserver 0.0.0.0:5000"
    ports:
      - '5000:5000'
    # depends_on:
    #   - upgrade
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - .env

  # upgrade:
  #   build: .
  #   image: app
  #   command: flask db upgrade
  #   volumes:
  #     - .:/usr/src/app
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres

  postgres:
    restart: always
    image: postgres:latest
    env_file:
      - .postgresenv
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always

volumes:
  db-data:
